# Generated by Django 4.1.2 on 2022-11-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('questionnaire', '0004_alter_questionnaire_blood_preasure_high_and_more'),
        ('appointment_report', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreport',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='equipment_list', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='appointmentreport',
            name='questionnaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
        ),
    ]
