# Generated by Django 4.1.2 on 2022-11-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('appointment_report', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentreport',
            name='equipment',
            field=models.ManyToManyField(related_name='equipment_list', to='equipment.equipment'),
        ),
    ]
