# Generated by Django 4.1.2 on 2022-11-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tranfusion_center', '0004_alter_tranfusioncenter_building_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-'), ('N', 'Unknown')], default='N', max_length=6)),
                ('amount_of_blood', models.PositiveBigIntegerField(default=0)),
                ('transfusion_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfusion_center.tranfusioncenter')),
            ],
        ),
    ]
