# Generated by Django 4.1.2 on 2022-10-23 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tranfusion_center', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('jmbg', models.CharField(blank=True, max_length=13, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Unknown')], default='N', max_length=1)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('workplace', models.TextField(blank=True, max_length=200, null=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('penalty_points', models.PositiveIntegerField(default=0)),
                ('is_activated', models.BooleanField(default=False)),
                ('tranfusion_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tranfusion_center.tranfusioncenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
