# Generated by Django 4.1.2 on 2022-10-26 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='jmbg',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
