# Generated by Django 4.1.2 on 2022-11-11 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_jmbg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='jmbg',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
