# Generated by Django 4.1.2 on 2022-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_jmbg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='penalty_deleted',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
