# Generated by Django 4.1.2 on 2022-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_penalty_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='penalty_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
