# Generated by Django 4.1.2 on 2022-10-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_userprofile_blood_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('less_than_50kg', models.BooleanField(blank=True, null=True)),
                ('flu', models.BooleanField(blank=True, null=True)),
                ('other_sickness', models.BooleanField(blank=True, null=True)),
                ('feel_good', models.BooleanField(blank=True, null=True)),
                ('changes_on_skin', models.BooleanField(blank=True, null=True)),
                ('blood_preasure_high', models.BooleanField(blank=True, null=True)),
                ('blood_preasure_low', models.BooleanField(blank=True, null=True)),
                ('using_medicine', models.BooleanField(blank=True, null=True)),
                ('last_medicine_in_last_7_days', models.BooleanField(blank=True, null=True)),
                ('on_menstruation_period', models.BooleanField(blank=True, null=True)),
                ('dental_interventions_in_last_7_days', models.BooleanField(blank=True, null=True)),
                ('tattoo_piercing_in_last_6_months', models.BooleanField(blank=True, null=True)),
                ('surgery_in_last_6_months', models.BooleanField(blank=True, null=True)),
                ('blood_tranfusion_in_last_6_months', models.BooleanField(blank=True, null=True)),
                ('pregnant', models.BooleanField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
