# Generated by Django 4.1.2 on 2022-10-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_jmbg'),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='last_medicine_before_7_days',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
