# Generated by Django 4.1.2 on 2022-10-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_remove_questionnaire_last_medicine_before_7_days_and_more'),
    ]