# Generated by Django 4.1.2 on 2022-11-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_remove_questionnaire_last_medicine_before_7_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='blood_preasure_high',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='blood_preasure_low',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='blood_tranfusion_in_last_6_months',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='changes_on_skin',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='dental_interventions_in_last_7_days',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='feel_good',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='flu',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='last_medicine_in_last_7_days',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='less_than_50kg',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='on_menstruation_period',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='other_sickness',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='pregnant',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='surgery_in_last_6_months',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='tattoo_piercing_in_last_6_months',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='using_medicine',
            field=models.BooleanField(),
        ),
    ]
