# Generated by Django 4.1.2 on 2022-11-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_jmbg'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ManyToManyField(related_name='staff_list', to='user_profile.userprofile'),
        ),
    ]
