# Generated by Django 4.1.2 on 2022-11-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tranfusion_center', '0005_alter_tranfusioncenter_building_number'),
        ('appointment', '0004_remove_appointment_date_time_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='transfusion_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tranfusion_center.tranfusioncenter'),
        ),
    ]
