# Generated by Django 4.1.2 on 2022-11-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_jmbg'),
        ('tranfusion_center', '0005_alter_tranfusioncenter_building_number'),
        ('appointment', '0005_alter_appointment_transfusion_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff_list', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='transfusion_center',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tranfusion_center.tranfusioncenter'),
            preserve_default=False,
        ),
    ]
