# Generated by Django 4.1.2 on 2022-11-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_jmbg'),
        ('appointment', '0008_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_profiles_that_canceled',
            field=models.ManyToManyField(blank=True, related_name='user_list', to='user_profile.userprofile'),
        ),
    ]
