# Generated by Django 4.1.2 on 2022-11-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_alter_userprofile_jmbg'),
        ('tranfusion_center', '0004_alter_tranfusioncenter_building_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='user_profile.userprofile')),
                ('transfusion_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfusion_center.tranfusioncenter')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user_profile.userprofile')),
            ],
        ),
    ]
