# Generated by Django 4.1.2 on 2022-11-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaints_responde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='responde',
            new_name='response',
        ),
    ]
