# Generated by Django 4.1.2 on 2022-11-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tranfusion_center', '0004_alter_tranfusioncenter_building_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('transfusion_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfusion_center.tranfusioncenter')),
            ],
        ),
    ]
