# Generated by Django 4.1.2 on 2022-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranfusion_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranfusioncenter',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tranfusioncenter',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
