# Generated by Django 4.1.2 on 2022-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranfusion_center', '0002_tranfusioncenter_city_tranfusioncenter_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranfusioncenter',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='tranfusioncenter',
            name='building_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
